### ISSUE TITLE
go-zsyncmake has been mirrored

### ISSUE THREAD

**Issue by probonopd** [orsonteodoro/oiledmachine-overlay#6]
https://github.com/orsonteodoro/oiledmachine-overlay/blob/519c5c5946d0f29dd8499585b815a825fefca8a9/profiles/package.mask#L60

>  On indefinte hold until deleted project and dependency go-zsyncmake are replaced.  Use app-arch/appimaged app-arch/appimagetool packages instead.

go-zsyncmake has been mirrored to https://github.com/probonopd/go-zsyncmake.

**Comment by orsonteodoro** [comment]
That's good news.  I thought it would be done or put back.  The go-appimage project will be continued to be monitored and ebuild distro package updated.
