### ISSUE TITLE
Howdy issues

### ISSUE THREAD

**Issue by Dzordzu** [orsonteodoro/oiledmachine-overlay#90]
I got some issues with `howdy`

## PAM modification
It would be great if ebuild could patch system-auth pam module to include `sufficient` line

## Xscreensaver
Pure installation was problematic. Fixed with
```
chmod 751 dlib-data
chmod 751 recorders
```

**Comment by orsonteodoro** [comment]
The equivalent XScreenSaver suggestion was applied, but the PAM modification is already suggested in pkg_postinst() with manual changes required.  The reason is that it requires manual changes is because of the possibility of custom system-auth configurations.

**Comment by Dzordzu** [comment]
I assume it as resolved. Thanks!
