### ISSUE TITLE
Make dev-python/contextlib2 support up to python3.12

### ISSUE THREAD

**Issue by fpemud** [orsonteodoro/oiledmachine-overlay#93]
I see that [contextlib2's READMErst](https://github.com/jazzband/contextlib2/blob/master/README.rst) has been updated:

> Versions currently tested in both tox and GitHub Actions are:
> 
> CPython 3.8
> CPython 3.9
> CPython 3.10
> CPython 3.11
> CPython 3.12
> PyPy3 (specifically 3.10 in GitHub Actions)

Thanks!

**Comment by orsonteodoro** [comment]
The tagged version lists 3.10.  I added the live ebuild instead.

**Comment by fpemud** [comment]
I have successfully using your dev-python/contextlib2-9999, thanks.
